version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1945:1945"
    environment:
      - NODE_ENV=production
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - DATABASE_URI=${DATABASE_URI}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
